name: Node CI

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
 
      - name: Install dependencies
        run : npm install       

      - name: Build Docker Image
        run: docker build -t node-ci-app .

      - name: Run the container
        run: docker run -p 8080:3000 node-ci-app 